packaging_format = 2

id = "mitra"
name = "Mitra"
description.en = "Federated micro-blogging platform."
description.fr = "Plateforme de micro-blogging fédéré"

version = "3.90~ynh1"

maintainers = ["Papa Dragon"]

[upstream]
license = " AGPL-3.0-only"
code = "https://codeberg.org/silverpill/mitra"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = ["amd64"]
multi_instance = false
ldap = false
sso = false
disk = "150M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    help.en = "Your website can only be installed in a root domain or subdomain"
    help.fr = "Votre site web ne peut être installé que dans un domaine racine ou un sous-domaine"
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://codeberg.org/silverpill/mitra/archive/8893ddf822b835a16eaa28c98470bb2aa376617f.tar.gz"
        sha256 = "a9d7d89b63125c2d0913c369fe40e04a5d8ff33580f463a3d6d0318c85c05225"
        autoupdate.strategy = "latest_forgejo_tag"
        autoupdate.version_regex = "^v(.*)$"

        [resources.sources.mitra-web]
        url = "https://codeberg.org/silverpill/mitra-web/archive/f0438be0defcea943eb7234240a07db3b71a19f7.tar.gz"
        sha256 = "22b64dc3733ddbd0c0f373a3cc3046ba578e5e45b972f963c7f686c425c126bf"
        autoupdate.upstream = "https://codeberg.org/silverpill/mitra-web"
        autoupdate.strategy = "latest_forgejo_release"
        autoupdate.version_regex = "^mitra-web_(.*)$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
