#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    test_upgrade_from.8fd0bef8eeb983e3a6fbcb46b73c713d7f5bf7d5.name = "Upgrade from 3.10.0~ynh1"

