#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR & DATA DIR
#=================================================
ynh_script_progression "Backup of install dir & data directories..."

ynh_backup "$install_dir"

ynh_backup "$data_dir"

#=================================================
# BACKUP CONFIG FILE
#=================================================
ynh_script_progression "Backup of Mitra server configuration..."

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/$app/config.yaml"

#=================================================
# BACKUP THE DATABASE
#=================================================
ynh_script_progression "Backup of the database..."

ynh_psql_dump_db > db.sql

#=================================================
# BACKUP CONFIG FILE
#=================================================
ynh_script_progression "Backup of various files..."

ynh_backup "/etc/$app"

#=================================================
# BACKUP LOGROTATE
#=================================================

ynh_backup "/etc/logrotate.d/$app"
ynh_backup "/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
