#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE SETTINGS
#=================================================
ynh_script_progression "Initialize installation settings..."

ynh_app_setting_set_default --key=admin --value=$(ynh_user_get_info --username=$admin --key=username)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from git forge
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# INSTALL MITRA
#=================================================

# We need this for the systemd script
ln -s $data_dir /var/lib/$app

# Download mitra deb file and install it.
dpkg --install --force-confnew "$install_dir/mitra.deb" || true
dpkg_install_failed=$(dpkg-query -f '${status} ${package}\n' -W | awk '$4 ~ /^mitra.*/ && $3 != "installed" {print $4}' | wc -l)

if [[ $dpkg_install_failed -ge 1 ]]; then
    ynh_die --message="The service mitra cannot be installed for now."
fi

# List systemd service in YunoHost
yunohost service add "$app" --description="Mitra server backend"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.example.yaml" --destination="/etc/$app/config.yaml"

ynh_store_file_checksum /etc/$app/config.yaml

#=================================================
# START SERVICE
#=================================================

ynh_systemctl --log_path="systemd"

#=================================================
# CREATE ADMIN
#=================================================
ynh_exec_as_app mitractl create-user $admin $adminpass admin

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring Nginx..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# SETUP LOGROTATE
#=================================================

#=================================================
# SETUP FAIL2BAN
#=================================================

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
