#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE SETTINGS
#=================================================
ynh_script_progression "Initialize installation settings..."

ynh_app_setting_set_default --key=admin --value=$(ynh_user_get_info --username=$admin --key=username)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from GitHub
ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir/dist" --source_id="mitra-web"


#=================================================
# INSTALL RUST/CARGO
#=================================================
ynh_script_progression "Installing Rust and Cargo..." --weight=1

# Install rustup with the toolchain needed by Mitra
pushd "$install_dir"
    ynh_hide_warnings ynh_exec_as_app \
        RUSTUP_HOME="$install_dir/.rustup" \
        CARGO_HOME="$install_dir/.cargo" \
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | ynh_hide_warnings ynh_exec_as_app sh -s -- -q -y
popd

#=================================================
# BUILD MITRA
#=================================================
pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app bash -c "source $install_dir/.cargo/env; cargo build --release --features production"
popd

ln -s $install_dir/target/release/mitra /usr/bin/
ln -s $install_dir/target/release/mitractl /usr/bin/

ynh_safe_rm "$install_dir/.cargo"
ynh_safe_rm "$install_dir/.rustup"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

mkdir /etc/$app

ynh_config_add --template="config.example.yaml" --destination="/etc/$app/config.yaml"

ynh_store_file_checksum /etc/$app/config.yaml

#=================================================
# CREATE ADMIN
#=================================================
ynh_exec_as_app mitractl create-account $admin $password admin

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Configuring log rotation..."

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate "/var/log/$app/$app.log"
ynh_exec_as_app touch "/var/log/$app/$app.log"

#=================================================
# SETUP & START SERVICE
#=================================================
ynh_config_add_systemd
yunohost service add "$app" --description="Federated micro-blogging platform"

ynh_script_progression "Starting $app's systemd service..."
ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring Nginx..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# SETUP LOGROTATE
#=================================================

#=================================================
# SETUP FAIL2BAN
#=================================================

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
