#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

ynh_systemctl --service="$app" --action="stop"
ynh_config_remove_systemd

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove other various files specific to the app... such as:

# Remove a directory securely
ynh_safe_rm "/etc/$app"

ynh_safe_rm "/usr/bin/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
