#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..." --weight=1

# Remove the service
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

ynh_systemctl --service="$app" --action="stop"
ynh_config_remove_systemd

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

ynh_safe_rm "/etc/$app"
ynh_safe_rm "/usr/bin/mitra"
ynh_safe_rm "/usr/bin/mitractl"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
