#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=admin --value=$(ynh_user_get_info --username=$admin --key=username)
ynh_app_setting_set_default --key=instance_title --value="Mitra on YunoHost"
ynh_app_setting_set_default --key=instance_short_description --value="Your federated micro-blogging platform"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from GitHub
ynh_setup_source --dest_dir="$install_dir"  --full_replace
ynh_setup_source --dest_dir="$install_dir/mitra-web-src" --source_id="mitra-web"  --full_replace

#=================================================
# INSTALL RUST/CARGO
#=================================================
ynh_script_progression "Installing Rust and Cargo..."

# Install rustup with the toolchain needed by Mitra
pushd "$install_dir"
    ynh_hide_warnings ynh_exec_as_app \
        RUSTUP_HOME="$install_dir/.rustup" \
        CARGO_HOME="$install_dir/.cargo" \
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | ynh_hide_warnings ynh_exec_as_app sh -s -- -q -y
popd

#=================================================
# BUILD MITRA
#=================================================

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app bash -c "source $install_dir/.cargo/env; DEFAULT_CONFIG_PATH=$install_dir/config.yaml cargo build --release --features production"
popd

ynh_safe_rm "$install_dir/.cargo"
ynh_safe_rm "$install_dir/.rustup"

#==============================================
# BUILD MITRA-WEB
#=================================================
ynh_script_progression "Building Web client... (a little more patience!)"

pushd "$install_dir/mitra-web-src"
	ynh_hide_warnings npm install --no-save
	ynh_hide_warnings npx allow-scripts
    echo "VITE_BACKEND_URL=" > .env.local
    ynh_hide_warnings npm run build
    mv dist $install_dir/
popd

chown -Rv $app:www-data $install_dir/dist

ynh_safe_rm "$install_dir/mitra-web-src"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.example.yaml" --destination="$install_dir/config.yaml"

ynh_store_file_checksum $install_dir/config.yaml

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Federated micro-blogging platform"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/__APP__/__APP__.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
